apiVersion: v1
kind: Service
metadata:
  name: pages-mysql
  namespace: beta2
  labels:
    app: pages
    tier: service
spec:
  ports:
    - port: 3306
  selector:
    app: pages
    tier: service
  type: NodePort