apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: beta2
spec:
  storageClassName: document
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi