apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: beta2
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/beta2"